version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: support_bot_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: support_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: support_bot_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
